### ISSUE TITLE
Creating a datasource does not include a database name in the connection string.

### ISSUE THREAD

**Issue by GaryStanton** [Ortus-Solutions/cfconfig#15]
When using the `datasource save` command, the database name is not entered into the connection string. 
Using MSSQL driver, Lucee 5 on latest version of Commandbox.
`cfconfig datasource save name=test dbdriver=MSSQL host=xxx.xxx.xxx.xxx port=xxx database=test username=test password=test`

The database name appears in the Lucee admin, but not in the connection string. 
`cfdbinfo` shows all tables from the `master` database.
Upon clicking on `update` in the Lucee datasource screen, the connection string is added and a subsequent `cfdbinfo` shows tables from the correct database.

**Comment by bdw429s** [comment]
Looks like the database name goes into the `custom` string.  You can add it manually by adding:
```
custom="DATABASENAME\=test"
```
to your command above.  But I'm also pushing a new version that should default that custom string for MSSQL data sources too.  Update and test pls.
