### ISSUE TITLE
Exporting config file of existing Coldfusion 2016 server configuration

### ISSUE THREAD

**Issue by timsayshey** [Ortus-Solutions/cfconfig#2]
I've really been digging into cfconfig and haven't been able to generate a config.json file from an existing server. Is that possible?

**Comment by bdw429s** [comment]
What command did you try and what happened when you tried it??  I've exported JSON config many times from a 2016 server.  Is this a CommandBox server, or a "regular" install.  For a 2016 server you've started with CommandBox, it should just look like this:

```bash
start cfengine=adobe@2016
cfconfig export config.json
```

**Comment by timsayshey** [comment]
Ah, that was it! Much thanks Brad 👊
