### ISSUE TITLE
Export/Import of scheduled tasks

### ISSUE THREAD

**Issue by JasPanesar** [Ortus-Solutions/cfconfig#20]
Hi, Thanks for making this package.   It's a great addition.

I was wondering if there is a way to handle the management of scheduled tasks in the cfconfig lexicon?

I did not see it listed in the documentation at: https://cfconfig.ortusbooks.com/using-the-cli/command-overview/export-settings

Thanks!
Jas

**Comment by bdw429s** [comment]
Hi @JasPanesar and thanks for the ticket.  Scheduled tasks are supported in Adobe ColdFusion but not yet in Lucee.  (A client paid for me to add the Adobe support).  I need to update the docs to include that.  So if you're on Adobe CF, then you're good to go.  If you're on Lucee then you can help add support if you like or wait until I get a chance to add it.  Of course, paying to get it added right away is always an option :)

**Comment by bdw429s** [comment]
I've put in a ticket for this over in our bug tracker so I'm closing this one for now.

https://ortussolutions.atlassian.net/browse/CFCONFIG-22
